import { findingLabel } from "./verdict";
import type { IdLocation, SuiteResult } from "./types";

export function endpointLine(opts: {
  method: string;
  urlTemplate: string;
  paramKey: string;
  paramLocation: IdLocation;
}): string {
  return `${opts.method} ${opts.urlTemplate}  ·  ${opts.paramLocation}:${opts.paramKey}`;
}

export function toCurl(opts: {
  method: string;
  url: string;
  headers: Record<string, string>;
  body: string;
}): string {
  const parts = [`curl -i -sS -X ${opts.method} ${shell(opts.url)}`];
  for (const [k, v] of Object.entries(opts.headers)) {
    if (!v) continue;
    parts.push(`  -H ${shell(`${k}: ${v}`)}`);
  }
  if (opts.body && opts.method !== "GET" && opts.method !== "HEAD") {
    parts.push(`  --data-raw ${shell(opts.body)}`);
  }
  return parts.join(" \\\n");
}

function shell(s: string): string {
  return `'${s.replace(/'/g, `'\\''`)}'`;
}

export function buildReportMarkdown(result: SuiteResult): string {
  const e = result.endpoint;
  const v = result.verdict;
  const lines: string[] = [];
  lines.push(`# ${v.title}`);
  lines.push("");
  lines.push(`**Class:** ${findingLabel(v.finding)} (${v.confidence} confidence)`);
  lines.push(`**Reportable per Witness rules:** ${v.reportable ? "YES" : "NO — do not submit as confirmed"}`);
  lines.push("");
  lines.push("## Endpoint");
  lines.push("```");
  lines.push(endpointLine(e));
  lines.push(`ID A (victim object): ${e.idA}`);
  lines.push(`ID B (attacker object): ${e.idB || "(not provided)"}`);
  lines.push("```");
  lines.push("");
  lines.push("## Summary");
  lines.push(v.summary);
  lines.push("");
  lines.push("## Evidence the tool used");
  for (const w of v.why) lines.push(`- ${w}`);
  if (v.whyNotConfirmed.length) {
    lines.push("");
    lines.push("## Why this is NOT marked confirmed (if any)");
    for (const w of v.whyNotConfirmed) lines.push(`- ${w}`);
  }
  lines.push("");
  lines.push("## Tests");
  lines.push("| Test | Identity | Object | Status | Bytes | Body kind |");
  lines.push("|---|---|---|---|---|---|");
  for (const t of result.tests) {
    lines.push(
      `| ${t.spec.title} | ${t.identityUsed} | ${t.objectId} | ${t.response.status ?? t.response.error ?? "-"} | ${t.response.byteLength} | ${t.classified.kind} |`,
    );
  }
  lines.push("");
  lines.push("## Reproduction");
  lines.push("1. Create two users (A victim, B attacker) authorized in-scope.");
  lines.push("2. As A, call the endpoint on A's object — save the JSON.");
  lines.push("3. As B, replay the same request with B's session and A's object id.");
  lines.push("4. Compare bodies. Impact = B reads A's private fields.");
  lines.push("");
  lines.push("## curl");
  for (const c of result.curls) {
    lines.push(`### ${c.label}`);
    lines.push("```bash");
    lines.push(c.command);
    lines.push("```");
    lines.push("");
  }
  lines.push("## Response snippets");
  for (const t of result.tests) {
    lines.push(`### ${t.spec.title} — ${t.response.status ?? "err"}`);
    lines.push("```");
    lines.push(t.response.body.slice(0, 1200) || t.response.error || "(empty)");
    lines.push("```");
    lines.push("");
  }
  lines.push("---");
  lines.push(
    `_Generated by Witness. Mode=${result.mode}. The tool never invents a confirmed finding without two identities and matching object evidence._`,
  );
  return lines.join("\n");
}
