/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as ApiDemoInsecureOrdersIdRouteImport } from './routes/api/demo/insecure/orders.$id'
import { Route as ApiDemoSecureOrdersIdRouteImport } from './routes/api/demo/secure/orders.$id'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiDemoInsecureOrdersIdRoute = ApiDemoInsecureOrdersIdRouteImport.update({
  id: '/api/demo/insecure/orders/$id',
  path: '/api/demo/insecure/orders/$id',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiDemoSecureOrdersIdRoute = ApiDemoSecureOrdersIdRouteImport.update({
  id: '/api/demo/secure/orders/$id',
  path: '/api/demo/secure/orders/$id',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/api/demo/insecure/orders/$id': typeof ApiDemoInsecureOrdersIdRoute
  '/api/demo/secure/orders/$id': typeof ApiDemoSecureOrdersIdRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/api/demo/insecure/orders/$id': typeof ApiDemoInsecureOrdersIdRoute
  '/api/demo/secure/orders/$id': typeof ApiDemoSecureOrdersIdRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/api/demo/insecure/orders/$id': typeof ApiDemoInsecureOrdersIdRoute
  '/api/demo/secure/orders/$id': typeof ApiDemoSecureOrdersIdRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    '/' | '/api/demo/insecure/orders/$id' | '/api/demo/secure/orders/$id'
  fileRoutesByTo: FileRoutesByTo
  to: '/' | '/api/demo/insecure/orders/$id' | '/api/demo/secure/orders/$id'
  id:
    | '__root__'
    | '/'
    | '/api/demo/insecure/orders/$id'
    | '/api/demo/secure/orders/$id'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  ApiDemoInsecureOrdersIdRoute: typeof ApiDemoInsecureOrdersIdRoute
  ApiDemoSecureOrdersIdRoute: typeof ApiDemoSecureOrdersIdRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/demo/insecure/orders/$id': {
      id: '/api/demo/insecure/orders/$id'
      path: '/api/demo/insecure/orders/$id'
      fullPath: '/api/demo/insecure/orders/$id'
      preLoaderRoute: typeof ApiDemoInsecureOrdersIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/demo/secure/orders/$id': {
      id: '/api/demo/secure/orders/$id'
      path: '/api/demo/secure/orders/$id'
      fullPath: '/api/demo/secure/orders/$id'
      preLoaderRoute: typeof ApiDemoSecureOrdersIdRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  ApiDemoInsecureOrdersIdRoute: ApiDemoInsecureOrdersIdRoute,
  ApiDemoSecureOrdersIdRoute: ApiDemoSecureOrdersIdRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
